### ISSUE TITLE
RFC: Support for SDFormat import

### ISSUE THREAD

**Issue by adamdbrw** [o3de/sig-simulation#80]
# Support for importing [SDFormat](http://sdformat.org/).

## Summary

This RFC proposes to implement [Simulation Description Format](http://sdformat.org/) (SDFormat, often abbreviated further to SDF) support in O3DE through new features of [ROS 2 Gem](https://github.com/o3de/o3de-extras/tree/3dd1e0214506c23daa758f4aa00045619f962be1/Gems/ROS2). Such support will enable users to import resources such as robots, worlds, and other models.

## What is the relevance of this feature?

Robotics is a domain for which O3DE is one of the best choices. Since O3DE is a relatively fresh platform in the domain, there are still insufficient assets such as robots, worlds, and models to quickly build robotic simulation. There are many such resources in the open source, most often in the SDFormat which is supported by Gazebo. These resources include plugins for (mostly) robots, which are referenced in the format. The plugins specify behaviors on top of the robot description, which make such SDF assets ready to simulate.

Providing a way to import SDFormat files in O3DE would greatly increase its attractiveness for robotics, especially for users with existing SDF assets. It might also result in contributing to open standards in robotic simulation through verifying the format with another engine. 

### Current Robot Import feature

Currently, there is a Robot Import feature in O3DE, which allows users to import robots in [Unified Robot Description Format (URDF)](http://wiki.ros.org/urdf/XML/model). It makes use of [urdfdom](https://github.com/ros/urdfdom/tree/ros2) library to parse files. The Robot Importer also supports [XACRO](https://github.com/ros/xacro/tree/ros2).
URDF support is important as it is the format most commonly used to describe real robots. However, SDFormat is more suitable for simulation since it includes information about behavior, required to properly simulate the robot.

### Conversion of URDF non-standard extensions

Open-source URDF assets (robot description packages) often employ XACRO for parametrization, which is already supported in the Robot Importer. However, they also typically use non-standard `<gazebo>` tags and specify plugins within. This is not supported by `urdfdom` and is also not part of the standard. Such practice of superimposing information about simulation behavior in URDF is obsolete and is being replaced by SDFormat. Regardless, many such assets exist. Fortunately, [SDFormat library](https://github.com/gazebosim/sdformat) includes a converter that can handle URDF assets as well.

### Improving import UX

URDF Robot Import is handled through a wizard tool. To provide a better user experience, the feature will include support for handling SDFormat (`.sdf`) files through asset builder, allowing users to drag `.procprefab` files into their scene.

Furthermore, re-import will be supported. SDFormat support in O3DE will be a process, and the field of available plugins as well as O3DE components is dynamic. Thus, users will benefit from the possibility of re-importing files with increased support as new versions of O3DE are released. This will be handled by assets` metadata.

### Migrating and building on `sdformat`

This RFC proposes to replace the parser used for the current Robot Importer, `urdfdom`, with `sdformat`. The code handling the actual construction of entities and components during the import process will remain almost the same, but the source of information used for this construction will be replaced.

Furthermore, with `sdformat`, a broader array of data types can be supported, including models and worlds, and a new set of plugins.

### Handling plugins

An important part of the feature's technical solution is handling of plugins. These are external libraries that realize certain behavior such as acquiring simulated sensor data.

Each plugin will map to a specific Gem and a set of components (typically one). The Gem will often be ROS 2 Gem, which already has plenty of components suitable for such mapping. However, an interface will be exposed to register new mappings, supporting the case of implementing support for new and custom plugins, through new Gems and components.

For sensors, configuration parameters necessary for the construction of corresponding components are contained in `<sensor>` and `<plugin>` tags together.

#### Plugin importer flow diagram

![PluginImport_v2](https://github.com/o3de/sig-simulation/assets/16702721/394052cc-8c03-4dd9-a05b-c61958b8fa8d)

#### Developer interface to extend the mapping

The base for the plugin import, i.e. the mapping between Gazebo plugins and O3DE components, will be extendable. The mapping will be based on the _SerializeContext_ reflection system. In particular,  O3DE Components that are designed to mirror the behavior of SDFormat sensors and/or plugins will register a specialized attribute tag. Next, the Robot Importer will find all active O3DE Components via _SerializeContext_ and check, if any of them can be used to import `sdformat` model 
 / world description into O3DE.

The user-defined mapping extension will be implemented within Gem's implementation by adding an O3DE Component with the properly defined reflection and a hook for translating parameters listed in SDFormat data into the component's parameters. 

#### SDF sensor tag mappings

* `camera sensor`: mapped to `ROS2CameraSensorComponent`
* `depth_camera`: mapped to `ROS2CameraSensorComponent`
* `contact`: mapped to `ROS2ContactSensorComponent`
* `imu`: mapped to `ROS2ImuSensorComponent`
* `lidar`: mapped to `ROS2LidarSensorComponent`
* `multicamera`: mapped to `ROS2CameraSensorComponent`
* `navsat`: mapped to `ROS2GNSSSensor`
* `rgbd_camera`: mapped to `ROS2CameraSensorComponent`

Some legacy sensor tags, such as `gps` or `gpu_ray` will be also supported.

#### Gazebo plugins support
* `libgazebo_ros_ackermann_drive`: mapped to Ackermann drive component
* `libgazebo_ros_bumper`: mapped to `ROS2ContactSensorComponent`
* `libgazebo_ros_camera`: mapped to `ROS2CameraSensorComponent`
* `libgazebo_ros_camera_utils`: mapped to `ROS2CameraSensorComponent`
* `libgazebo_ros_depth_camera`: mapped to `ROS2CameraSensorComponent`
* `libgazebo_ros_diff_drive`: mapped to Vehicle Dynamic and Wheel Odometry components
* `libgazebo_ros_gps_sensor`: mapped to `ROS2GNSSSensorComponent`
* `libgazebo_ros_imu_sensor`: mapped to `ROS2ImuSensorComponent`
* `libgazebo_ros_joint_pose_trajectory`: new implementation
* `libgazebo_ros_joint_state_publisher`: new implementation
* `libgazebo_ros_multicamera`: mapped to `ROS2CameraSensorComponent`
* `libgazebo_ros_p3d`: mapped to `ROS2OdometrySensorComponent`
* `libgazebo_ros_planar_move`: mapped to `JointsTrajectoryComponent` and `JointsManipulationComponent` 
* `libgazebo_ros_ray_sensor`: mapped to `ROS2LidarSensorComponent`
* `libgazebo_ros_control`: mapped to `JointsTrajectoryComponent` and `JointsManipulationComponent`
* `libgazebo_ros_control-system`: mapped to `JointsTrajectoryComponent` and `JointsManipulationComponent`
* `libgazebo_ros_skid_steer_drive`: mapped to Vehicle Dynamic and Wheel Odometry components
* `libgazebo_ros_vacuum_gripper`: mapped to `VacuumGripperComponent`

O3DE components will be extended accordingly to bridge the gap between configurations of Gazebo plugins and O3DE components, prioritizing the most important parameters.

### Representation in the ROS 2 Gem.

SDFormat support will be realized through Robot Import feature, available both through a menu option and through support for dragging SDFormat files. Changes to the Gem include:

- Adding sdformat13 library as dependency through https://github.com/o3de/o3de-extras/pull/426.
- Supporting SDFormat in Asset Processor and Asset Browser, through SDFAssetBuilder introduced in https://github.com/o3de/o3de-extras/pull/432, and through subsequent changes.
- Updated and improved Wizard as outlined in [Robot Import documentation](https://development--o3deorg.netlify.app/docs/user-guide/interactivity/robotics/importing-robot/)
- Modified classes in Robot Importer as present in the [current code](https://github.com/o3de/o3de-extras/tree/3dd1e0214506c23daa758f4aa00045619f962be1/Gems/ROS2/Code/Source/RobotImporter). These are responsible for creating entities and components based on the imported asset structure.
- Mapping between sensors/plugins and O3DE gems and components will be included in the Robot Importer, for all known mappings using O3DE, ROS 2 Gem, and RGL Gem components.
- There will be a reflection hook for user-defined mappings, allowing developers to add new plugins and support them with gems and components. This will work similarly to AssetBuilder registration system, using SerializeContext reflection system.

The work will be supported by adding the most common SDFormat sensors that are still missing in the ROS 2 Gem. For example, the contact (bumper) sensor [has already been added](https://github.com/o3de/o3de-extras/pull/418). 

## What are the advantages of the feature?

Users are able to import robots, worlds, and models in SDFormat into O3DE. This improves the attractiveness of O3DE for robotics, makes the onboarding process easier, and allows developers to use their existing assets with O3DE.

## What are the disadvantages of the feature?

None

## Are there any alternatives to this feature?

No alternatives, but other formats could be prioritized first, such as USD. However, SDFormat seems to be a better match for O3DE as the most important one to support.

## How will users learn this feature?

Documentation and tutorial / demo content. [Current documentation](https://development--o3deorg.netlify.app/docs/user-guide/interactivity/robotics/importing-robot/) will be extended.

**Comment by nick-l-o3de** [comment]
This sounds like an excellent way to support a scene format.  There's basically 2 "autoupdating" ways to do it, in O3DE.  One is to write a native Asset Builder (plenty of examples) that watches for *.sdf and uses the asset processor to process it (into procprefab or whatever).  I recommend, if possible, using the Python Asset Builder framework for that, which lets you write an asset builder (that watches for a certain file type and then transforms it into a target output) completely in python for maximum flexibility.
Doing it this way would cause it to automatically send any SDF files to your asset builder, and also, re-send them if they change, or any declared dependencies change, or whenever the asset builder changes its own fingerprint and version, giving you quite a lot of control

The other way to do it is to instead write a Scene Processing plugin.   The Scene System is meant for ingesting entire scenes that have meshes, colliders, animations, etc, and output as Atom Meshes, Atom Materials, and so on.  If SDFormat contains these things, its likely you'd instead want a Scene Processing plugin, rather than just a raw asset builder. ...  Its currently used for ingesting FBX, DAE, OBJ, STL, and several other formats.   The Scene Processing system itself is an actual Asset Builder, so it works the same in that it monitors these input formats.  However, the scene processing system is a lot more complex and allows you to plug in pieces into it in several places.

1. The scene file is read into a input-format-independent in-memory scene graph (consisting of nodes and relationships between them).  You can write a 'importing' plugin to control this part, the plugin is responsible for being fed the input file and as it iterates over the input file, and building the scene in memory from it.   The input plugin doesn't make any judgement calls about what data to filter out or what data will be used for, its only job is to consume the input format and turn it into an in-memory scene.  This is why O3DE can read FBX, DAE, OBJ, etc.  The ingestion step is separate from how it is then used.  You can write an Ingestion plugin in a gem, and its all done via bus and callbacks.

2. Once the scene is built in memory, it is now a fully traversable scene graph that queries can be made against to walk it or iterate it and so on.   The next step is to start exporting it from this scene in memory into the final pieces that make up the output files.  This is done by a series of EXPORTING plugins combined with whats known as a Scene Manifest.   A scene manifest is a recipe that tells the exporting plugins and system what to actually do with the scene.  For example, the manifest might say to take certain nodes in the scene and turn it into an ATOM mesh for rendering, but a different set of nodes in the scene and turn it into a PHYSX collision file for use in colliders.  

The decision of what to do here is interesting because its pluggable, you can plug in a python script in here and _generate_ these recipe instructions of what to do with what nodes.  An example of this is the existing FBX->procprefab support - a plugin looks at the scene and uses a heuristic to find meshes, and tags them as to be exportable as meshes for atom, but also, it takes note of the ones it chose to do that with and their transforms, and at the same time, uses that data to write a procprefab file with the transform heirarchy and components already assigned.    The default system also has a bunch of naming conventions and heuristics, which choose what to export if no user-generated recipe file is present.  You can see the recipe it heuristically arrives with by right clicking on any scene file in the asset browser (For example FBX) and choosing 'edit scene settings'.  That GUI that appears is actually the scene manifest, you are modifying that 'recipe' that decides what to do with the scene.  You'll also notice that you can assign a python script here, which will also be able to programattically iterate over the scene graph to inspect it and choose to emit things into meshes, materials, etc based ont he contents of the scene.  The scene can also be **modified** in this step.

3.  Once the recipe has been decided/generated/loaded, the exporting plugins run (such as atom material or mesh exporter).  The procprefab system also runs here, using the data it collected/generated earlier during scene analysis.   Exporting, modifying, and importing plugins can live in any gem.

**Comment by adamdbrw** [comment]
Thank you for your feedback @ahcorde!
Our ongoing implementation is aiming for a release of the first version of the feature, but we are considering the feature as a whole here. 
I think the key to some of your questions lies in the mapping between plugins and components:

Why some types of sensors but not all? 
- We have components for a number of sensors already (lidars, cameras, IMU, ...), but not for every sensor. Supporting Altimeters and such would require us to first implement the components. This can be easily done either as a part of the Gem or as a separate Gem (which is similar, but not the same as Gazebo plugin). However, this is another kind of task (not "sensor import support", but more basic "sensor support"). Note that we have made exception for the Contact/Bumper plugin since we determined it is quite common. Our preliminary work included analyzing SDFs in the wild.
- These sensor plugins are great candidates for contributions! 

Two kinds of plugins
- O3DE, unlike Gazebo, does not bridge to ROS. The components include publishers / subscribers / action servers and so on and expose their parametrization to the user already. You can write ROS 2 code in O3DE directly. Thus, only one kind of plugin is needed.

Offline conversion tool:
- We produce a prefab on successful import. Which can be used to spawn one or many-of. A prefab and its resources can be results of offline tool processing (also involving AssetProcessor), though I imagine such tools would have to replicate Robot Importer wizard behavior and interactivity with the user, and thus they seem redundant at the moment. Note that we ask the user whether they want certain options, inform them about changes on import (such as due to duplicate naming or missing inertial), and provide information about next steps. Since compiled asset formats are specific to O3DE, the tool would not be that useful in my opinion.
- The whole import process has an API which can be used to import (convert) a bunch of SDFs in one go. We are already using this for automated testing.

Let me know if this clarifies some things for you and if you have more questions, please feel welcome!
